### ISSUE TITLE
hoverとスクロールのエフェクト

### ISSUE THREAD

**Issue by ehnh** [cyder/cyder-website#101]
hover（参考：http://ianlunn.github.io/Hover/ ）
・topとcontactのグレーのボタンにSweep to right
・topとproductの白縁ボタンにFade
・topとnewsの記事画像にSweep to top

スクロール
・topの一番上の背景を固定（参考：http://coliss.com/articles/build-websites/operation/css/css-alternate-fixed-scroll-backgrounds-by-codyhouse.html ）
・デザイン変わるけどスクロールアイコンもアニメーションつけたい（これの7とか10とか　http://www.nxworld.net/tips/css-scroll-down-button.html ）
~~・Aktivaサイトにアニメーション（理想はこんなん→http://on-ze.com/ ）~~ #102 へ移動 by @Nishihara-Daiki

できる範囲でいいのでよろしく

**Comment by Nishihara-Daiki** [comment]
保留
