### ISSUE TITLE
「わくわく」のカーソルアニメーション

### ISSUE THREAD

**Issue by ehnh** [cyder/cyder-website#115]
topページの「わくわく」のそれぞれの文字（わ、く、わ、く）が、カーソルを動かすことによって「」内を上下に揺れるアニメーション。
ついでに「」ももうちょっと広くとって欲しい。

<img width="476" alt="2017-06-07 03 29 05" src="https://user-images.githubusercontent.com/12541460/26845477-7e3e4854-4b31-11e7-97c4-9e6a327713eb.png">

ご検討くださいませ。

**Comment by mori-atsushi** [comment]
鬼畜ぅ！

> カーソルを動かすことによって。

もうちょっと具体的にイメージを伝えてくれると助かるかも。
hoverすると上下に動くようになるのか、カーソルの動きに付随して動作するのか。

**Comment by ehnh** [comment]
付随っすね！

**Comment by ehnh** [comment]
これに関して考えてるのは、「カーソルを動かす」という動作に付随してわくわくの文字が動くアニメーション

代替案として
サイト表示時に文字が一つずつ下から出てくるアニメーション
もいいかな（両方やってもいいしw）

トップページに何かしら動的な要素を入れたいなと思ってる。

**Comment by Nishihara-Daiki** [comment]
@ehnh 
> 「カーソルを動かす」という動作に付随してわくわくの文字が動くアニメーション

カーソルって、マウスポインタのことだよね？
カーソルをどう動かしたら、わくわくがどう動いてほしい？下記詳細願います
+ 発火条件(何をしたらアニメーション発動するのか)
  - 画面ロード時も？
  - マウス座標が変わる都度？
+ 時間
  - マウスを動かしている間だけ？
  - マウスを動かした瞬間xx秒？
  - 動かし終わった後xx秒持続？
+ 動作
  - いつも同じパラメータで上下に細かく振動？ (振動なら、回転を加えることもできそう)
  - あるいは、マウスの座標・速度・加速度などによって、振動の動きが変わる？
    * だとすれば、どう動く？
+ 動作環境
  - PC版のみ？スマホ版は何か別の挙動？

**Comment by ehnh** [comment]
- 発火条件
画面ロード完了後マウス座標が変わる都度。
こんな風に文字が最後に現れたら尚良し。
http://www.kudostyle.jp/

- 時間
マウスを動かしている間だけで、動かし終わった後3秒くらいかけて減速して止まる（できれば）

- 動作
正直見てみないとわからんけど、マウスのy方向の速度（検出できる？）に合わせて上下に動くと良い。

- 動作環境
pcのみ。
てか「もっと日常に〜」が１行の時だけで良い。

**Comment by Nishihara-Daiki** [comment]
@ehnh おーけー 👍  あと１つ
> マウスのy方向の速度（検出できる？）に合わせて上下に動く

検出はできるよ（多分
マウスのy方向速度に合わせて、振動の、周波数を可変？振幅を可変？
実装してみないと、処理の重さとか、動きとか分からんかな？とりあえず、振動周波数を変えて作ってみるね

**Comment by Nishihara-Daiki** [comment]
@Mori-Atsushi 相談。アニメーションをなるべくCSSで実装したいが、色々試した結果、上記わくわく上下をCSSで実装すると複雑になりそう
jQueryだけでアニメーション作ろうかと思うけど、どうでしょう？→ファイルは分けますか？
