### ISSUE TITLE
iOS端末のtopページ背景画像表示バグ

### ISSUE THREAD

**Issue by ehnh** [cyder/cyder-website#122]
iOS端末でtopページの背景画像が以下のように表示されるバグ

iphone safari
![image uploaded from ios 1](https://user-images.githubusercontent.com/12541460/26863224-3e696af0-4b8c-11e7-86a7-c33cc72bba5c.jpg)

iphone chrome
![image uploaded from ios](https://user-images.githubusercontent.com/12541460/26863242-540e3570-4b8c-11e7-890f-a1a27f97fde4.jpg)

ipad safari
![af699427-7300-46f3-bf66-6915d12be68d](https://user-images.githubusercontent.com/12541460/26863249-61a560a0-4b8c-11e7-86ed-97f09e4fc502.PNG)

**Comment by mori-atsushi** [comment]
background-attachment:fixed; が効かない環境によるものだと思われる。
http://qiita.com/volkuwabara/items/bedaf09244f5cdebb228

**Comment by Nishihara-Daiki** [comment]
あ、js での要素取得が、idじゃなくてclassになってるぞ・・・
@Mori-Atsushi 直す？
