### ISSUE TITLE
FaMirror実績追加

### ISSUE THREAD

**Issue by ehnh** [cyder/cyder-website#123]
NEWSに追加しましょう！

**Comment by mori-atsushi** [comment]
## KANAZAWAオープンデータアプリコンテスト2015 グランプリを受賞しました。
### 2015年12月5日
2015年12月5日に、金沢21世紀美術館レクチャーホールでKANAZAWAオープンデータアプリコンテスト2015の2次審査が行われました。
私たちのグループ（旧称：FaMirror Project）はタブレット向けWebアプリ「FaMirror」を発表し、グランプリを受賞しました。
![20151212210522](https://user-images.githubusercontent.com/13435109/27585530-a7026670-5b77-11e7-8a38-ed1ef8e39aa9.png)
http://www4.city.kanazawa.lg.jp/11010/appcontest/old/2015.html

## LODチャレンジ2015にてYahoo! JAPAN賞を受賞しました。
### 2016年3月19日
タブレット向けWebアプリ「FaMirror feat. LOD」が、Linked Open Data チャレンジ Japan2015のアプリケーション部門において、Yahoo! JAPAN賞に選ばれました。
2016年3月19日には優秀作品発表会が行われ、私たちもブース展示を行いました。
![rimg4370](https://user-images.githubusercontent.com/13435109/27586217-6bfa3c58-5b7a-11e7-9292-b0981a795fe2.jpg)
http://lodc.jp/2015/concrete5/blog/2016-02-19

**Comment by mori-atsushi** [comment]
文章の校正お願いします。

**Comment by Nishihara-Daiki** [comment]
誤：KANAZAWAオープンデータ**アプアリ**コンテスト2015 グランプリを受賞しました。
正：KANAZAWAオープンデータ**アプリ**コンテスト2015 グランプリを受賞しました。

誤：KANAZAWAオープンデータ**アプアリ**コンテスト2015
正：KANAZAWAオープンデータ**アプリ**コンテスト2015

**Comment by Nishihara-Daiki** [comment]
LODチャレンジ2015
Linked Open Data チャレンジ Japan2015
表記揺れは構わない？

**Comment by mori-atsushi** [comment]
タイトルは長過ぎてて略称を使うようにしようかなと思ったけど、どうでしょう。わかりにくいかな。

**Comment by Nishihara-Daiki** [comment]
Japanも略していい？

**Comment by mori-atsushi** [comment]
公式サイト内でも省略されてる形は多い
というか、公式サイト内の表記ゆれが激しい（Japanのありなし、Challangeの英語or日本語）
http://2016.lodc.jp/
