### ISSUE TITLE
robot.txtの設定

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#153]
以下のドメインを検索で引っかからないよう設定する
[http://cyder.sakura.ne.jp/cyder-website-dev/](http://cyder.sakura.ne.jp/cyder-website-dev/)
[http://cyder.sakura.ne.jp/cyder-website/](http://cyder.sakura.ne.jp/cyder-website/)

以下のドメインのみ表示する
[http://cyder.tech](http://cyder.tech)

**Comment by Nishihara-Daiki** [comment]
@Mori-Atsushi `rel="canonical"` を使うのはいかがでしょうか
https://ferret-plus.com/1809

**Comment by mori-atsushi** [comment]
よさそう
