### ISSUE TITLE
共通部分PC用css

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#24]
## 作成ファイル
共通するPC用cssを作成する。
* pc.css：横幅1024px〜を対象とする。

## 対象ページ
* top(index.html)
* about(about/index.html)
* news(news/index.html)
* product(product/index.html)
* contact(contact/index.html)

**Comment by mori-atsushi** [comment]
さらにこれやります。

**Comment by Nishihara-Daiki** [comment]
ファイル名、合わせた方が良いのでは
PC: 1024.css
Tablet: tablet.css -> 768.css

**Comment by Nishihara-Daiki** [comment]
実際は、 1024.css なんて存在しなかったのね・・・

**Comment by mori-atsushi** [comment]
pcの方をpc.cssに合わせる
