### ISSUE TITLE
newsページPC用css作成

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#38]
## 作成ファイル
newsページPC用cssを作成する。
* news.css内に記述
* 1024px〜に対応

## 対象ページ
* news(news/index.html)

## デザイン
![web_news](https://cloud.githubusercontent.com/assets/13435109/26042555/720686a4-3971-11e7-9e94-effa08025bf9.png)

**Comment by Mori-Atsushi** [comment]
#16 と統合
