### ISSUE TITLE
contactページPC用cssを作成する

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#40]
## 作成ファイル
contactページPC用cssを作成する。
* contact.css内に記述
* 1024px〜に対応

## 対象ページ
* contact(contact/index.html)

## デザイン
![web_contact](https://cloud.githubusercontent.com/assets/13435109/26042635/f207f112-3971-11e7-88aa-13a365073cd4.png)

**Comment by Nishihara-Daiki** [comment]
@ehnh @Mori-Atsushi "必須項目" の注釈をどこに入れるか、考えて欲しい

**Comment by Nishihara-Daiki** [comment]
#81 の案で、治ってました
修正、マージしてから考えましょ
