### ISSUE TITLE
英語を正す

### ISSUE THREAD

**Issue by Nishihara-Daiki** [cyder/cyder-website#50]
PRODUCT → PRODUCTS
kosien → koshien

**Comment by mori-atsushi** [comment]
kosien問題はここに追記しました。

**Comment by Nishihara-Daiki** [comment]
SEND は Submit では・・・

**Comment by mori-atsushi** [comment]
これはボタンのキャプションも？

**Comment by Nishihara-Daiki** [comment]
ボタンのキャプション？

**Comment by mori-atsushi** [comment]
ここ？
![2017-06-07 11 26 04](https://user-images.githubusercontent.com/13435109/26859641-1b94ae30-4b74-11e7-9cb9-4dc7e9ce45de.png)

**Comment by Nishihara-Daiki** [comment]
逆にそれ以外のどこ

**Comment by mori-atsushi** [comment]
なるほど、ここはSENDでいいんじゃないかな。

**Comment by Nishihara-Daiki** [comment]
"SEND" 見たことない
（そのそも英字送信ボタンを見る機会がほとんどないが

**Comment by Nishihara-Daiki** [comment]
ファイル名・ディレクトリ名への反映もお忘れなく
(追跡云々の都合上、 git から変更した方がいいのかな？)

**Comment by mori-atsushi** [comment]
SubmitよりSENDの方が伝わりやすいと思って。日本人の馴染みのある英語的に。

![2017-06-07 11 31 37](https://user-images.githubusercontent.com/13435109/26859753-e8467ba2-4b74-11e7-88f9-8565ece36497.png)

**Comment by Nishihara-Daiki** [comment]
> SubmitよりSENDの方が伝わりやすいと思って

🆗
