### ISSUE TITLE
Aktiva特設サイトスマホ用css作成

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#57]
Aktiva特設サイト(product/aktiva.html)用のスマホ用cssを作成する

## 作成ファイル
* css/aktiva.css

### スマホ版
![iphone_aktiva](https://cloud.githubusercontent.com/assets/13435109/26042410/2d1876ac-3970-11e7-811b-a754b2d083d8.png)

**Comment by mori-atsushi** [comment]
西原さんがお忙しいみたいなので、これ僕がやりますぜ。

**Comment by mori-atsushi** [comment]
@ehnh ここの比類なきダンス体験のとこの背景画像もらえますか。

**Comment by mori-atsushi** [comment]
@ehnh aktiva-image.pngのグレー版、もしくは透過度を教えてもらえませんか？
![aktiva_image](https://cloud.githubusercontent.com/assets/13435109/26712125/15b7928e-47a0-11e7-97b7-bf63ab119216.png)

**Comment by ehnh** [comment]
不透明度60%くらいかなー。
デザイン案の方はもうちょっと暗いけど
