### ISSUE TITLE
ヘッダメニューの修正

### ISSUE THREAD

**Issue by Nishihara-Daiki** [cyder/cyder-website#65]
## ヘッダの隙間修正
タブレット＆PC用のヘッダのメニューの隙間を修正
inline-block 使用しつつ、 `<li>` 要素間にスペースが入っているので、それが入ってしまっている
こちらを参考に直してください
http://qiita.com/BEMU/items/0f500e0306471073ed63

## その他ヘッダ修正
・ヘッダメニューのそれぞれの文字が右に寄ってる
・Cyderロゴがちょっと下になってる。それともっと大きくして欲しい
・snsアイコンもう少し小さく。
・メニュー項目をもう左にして右側に少しの余白を
・ヘッダの幅（高さ？）をもう少し大きくして上下の余白が欲しい
・全体的にメニュー項目同士の余白も広げてくれると良い

http://mataemon.jp/
ここのヘッダがイメージに近い

**Comment by mori-atsushi** [comment]
このIssueは西原さんにお願いしたい。

**Comment by mori-atsushi** [comment]
@ehnh ヘッダ関係の問題はここにコメントしてもらえますか？

**Comment by ehnh** [comment]
前書いたやつのコピペ↓
・ヘッダメニューのそれぞれの文字が右に寄ってる
・Cyderロゴがちょっと下になってる。それともっと大きくして欲しい
・snsアイコンもう少し小さく。
・メニュー項目をもう左にして右側に少しの余白を
・ヘッダの幅（高さ？）をもう少し大きくして上下の余白が欲しい
・全体的にメニュー項目同士の余白も広げてくれると良い

http://mataemon.jp/
ここのヘッダがイメージに近い

**Comment by mori-atsushi** [comment]
これは @Nishihara-Daiki さんお願いします。
