### ISSUE TITLE
OGP設定

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#90]
facebookやtwitterで共有したときのサムネイルや説明文の指定。

## 参考
https://ferret-plus.com/610

**Comment by mori-atsushi** [comment]
@ehnh facebookとかに表示させるサムネイル用の画像をもらえませんか？

## 条件
* 1200 x 630 px
* PNG
* 以下のサイトでイメージの確認を出来ます。
  * http://ogimage.tsmallfield.com/

**Comment by ehnh** [comment]
<img width="1235" alt="2017-06-05 06 44 22" src="https://cloud.githubusercontent.com/assets/12541460/26765626/930a89b4-49ba-11e7-9567-1bb0bd699e87.png">
<img width="1229" alt="2017-06-05 06 44 46" src="https://cloud.githubusercontent.com/assets/12541460/26765627/931a7072-49ba-11e7-8ac9-637919b5b90c.png">

選んで。

**Comment by ehnh** [comment]
<img width="1228" alt="2017-06-05 07 17 12" src="https://cloud.githubusercontent.com/assets/12541460/26765837/394b1b82-49bf-11e7-8db7-7a997d39b4ee.png">

**Comment by mori-atsushi** [comment]
もっと日常に「わくわく」を（上下の揺らぎなし）かな

**Comment by ehnh** [comment]
「」はつけとく？

**Comment by mori-atsushi** [comment]
つけましょう！

**Comment by ehnh** [comment]
ドライブの
素材>webサイト>写真（加工）
にogp.png上げた。
