### ISSUE TITLE
デザイン修正

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#97]
デザイン面で気になる点をできればスクショ付きで上げてください。

## 全体
* ProductのREAD MORE、CONTACT USみたいに他のボタン同じサイズの方が綺麗に見える気がする。
* 以下の部分に太字＆矢印の位置矯正&hover欲しいですw
    * hoverは半透明
    * 矢印はアイコン化したほうがよさそう
<img width="790" alt="2017-06-07 02 18 51" src="https://user-images.githubusercontent.com/12541460/26842411-b6203c82-4b27-11e7-953b-8c711f7588bf.png">

* ヘッダが大きくなったときにトップを降ろさなかったから微妙に食い込んでるな
![2017-06-07 13 35 47](https://user-images.githubusercontent.com/13435109/26862448-43832d60-4b86-11e7-8303-8fb9a19f02ca.png)

## aboutページ
* スマホの時はいいけどPCだと肩書きの文字が小さくて読みづらいかな
<img width="170" alt="2017-06-07 02 47 44" src="https://user-images.githubusercontent.com/12541460/26843580-b67b974a-4b2b-11e7-82d4-fb7ef2e6a134.png">

## News詳細
* 本文よりリンクの方が若干文字大きい？ 後リンクにhover欲しい（下線がいいかな）
<img width="576" alt="2017-06-07 03 02 53" src="https://user-images.githubusercontent.com/12541460/26844294-df7b48d2-4b2d-11e7-98be-67a2779b4bf1.png">

## お問い合わせページ
* タブレットやPCだとお問い合わせ内容の長方形が横長すぎるかも。高さを今の２倍くらいにしてもいいと思う。

**Comment by mori-atsushi** [comment]
スマホビュー時はそんなに気にならないけど、タブレットやPCだとお問い合わせ内容の長方形が横長すぎるかも。
高さを今の２倍くらいにしてもいいと思う。
by @ehnh

**Comment by ehnh** [comment]
全体だからこっちに書くけど、ProductのREAD MORE、CONTACT USみたいに他のボタン同じサイズの方が綺麗に見える気がする。

**Comment by ehnh** [comment]
topページproduct部分とProductページの、説明文、ボタンの位置を合わせる。

**Comment by mori-atsushi** [comment]
ここのhoverいりませんか？下線とかあってもいい気がする。

![2017-06-07 2 15 22](https://user-images.githubusercontent.com/13435109/26842272-341281c8-4b27-11e7-9121-fa42313a878b.png)

**Comment by ehnh** [comment]
太字＆矢印の位置矯正&hover欲しいですw

**Comment by mori-atsushi** [comment]
hoverは上のメニューと合わせて半透明でもいい気がする
矢印の補正ってのは `>` のことかな？フォントの関係でちょっと下になっちゃってるな。

**Comment by ehnh** [comment]
<img width="790" alt="2017-06-07 02 18 51" src="https://user-images.githubusercontent.com/12541460/26842411-b6203c82-4b27-11e7-953b-8c711f7588bf.png">
半透明でいいよー
見た目はこれに近づけてもらえると

**Comment by mori-atsushi** [comment]
画像は入力フォームにドラックでいけるよ。（そっちのほうがslackにも貼り付けられて良い。
その矢印は画像のほうが良さげかも？

**Comment by ehnh** [comment]
入力フォームにドラッグしたよ。

**Comment by ehnh** [comment]
素材>Webサイト>アイコン・透過素材に「right_arrow.png」上げた。

**Comment by ehnh** [comment]
<img width="170" alt="2017-06-07 02 47 44" src="https://user-images.githubusercontent.com/12541460/26843580-b67b974a-4b2b-11e7-82d4-fb7ef2e6a134.png">
スマホの時はいいけどPCだと肩書きの文字が小さくて読みづらいかな

**Comment by ehnh** [comment]
<img width="576" alt="2017-06-07 03 02 53" src="https://user-images.githubusercontent.com/12541460/26844294-df7b48d2-4b2d-11e7-98be-67a2779b4bf1.png">
本文よりリンクの方が若干文字大きい？
後リンクにhover欲しい（下線がいいかな）

**Comment by mori-atsushi** [comment]
ヘッダが大きくなったときにトップを降ろさなかったから微妙に食い込んでるな
![2017-06-07 13 35 47](https://user-images.githubusercontent.com/13435109/26862448-43832d60-4b86-11e7-8303-8fb9a19f02ca.png)

**Comment by mori-atsushi** [comment]
だいぶ溜まってきたので、上部のコメントでまとめました。
