### ISSUE TITLE
文章修正

### ISSUE THREAD

**Issue by mori-atsushi** [cyder/cyder-website#98]
文章面で気になる所があればコメントで挙げてください。

* newsのalt属性の変更
* 明石ケーブルテレビのnewsの文章変更。
* Cyderは一緒に活動したい学生や協力して頂ける企業を募集します。
↓
Cyderは一緒に活動したい学生や協力して頂ける企業を募集しています。

**Comment by Nishihara-Daiki** [comment]
news/kosien170309.html
```html
<img src="../images/news/kosien170309.jpg" alt="kosien">
```
alt属性、日本語にするか、半角でも koshien にする派です
何れにしても、"甲子園"だけでは、言葉が足りないような・・・

**Comment by Nishihara-Daiki** [comment]
alt属性については、全体的に見直した方が良いかもしれません

**Comment by ehnh** [comment]
今気づいたけど、明石ケーブルテレビでAktiva(旧称: 舞鏡)が紹介されました。の記事の文章が起業家甲子園になってますね。

**Comment by mori-atsushi** [comment]
やばすぎなのでは

**Comment by mori-atsushi** [comment]
公開前にこれをやります。一旦全体的に確認して頂けると幸いです。

**Comment by ehnh** [comment]
Cyderは一緒に活動したい学生や協力して頂ける企業を募集します。
↓
Cyderは一緒に活動したい学生や協力して頂ける企業を募集しています。
